# Renamed EPA Dataset Merging

In [1]:
# Read in libs
import pandas as pd

## Step 1. Read in Data

In [2]:
# Read in 2008-2009 datasets
epa_0809_siteinfo = pd.read_excel('0809phabmed_renamed.xlsx')
epa_0809_phab = pd.read_excel('0809phabmed_renamed.xlsx')
epa_0809_land = pd.read_excel('epa_0809_land_renamed.xlsx')
epa_0809_chem = pd.read_excel('epa_0809_chem_renamed.xlsx')
# Read in 2013-2013 datasets
epa_1314_siteinfo = pd.read_excel('nrsa1314_siteinfo_renamed.xlsx')
epa_1314_phab = pd.read_excel('nrsa1314_phab_renamed.xlsx')
epa_1314_land = pd.read_excel('epa_1314_land_renamed.xlsx')
epa_1314_chem = pd.read_excel('epa_1314_chem_renamed.xlsx')
# Read in 2018-2019 datasets
epa_1819_siteinfo = pd.read_excel('nrsa_1819_siteinfo_renamed.xlsx')
epa_1819_phab = pd.read_excel('nrsa_1819_phab_renamed.xlsx')
epa_1819_land = pd.read_excel('epa_1819_land_renamed.xlsx')
epa_1819_chem = pd.read_excel('epa_1819_chem_renamed.xlsx')

## Step 2. Drop rows without the target

In [3]:
# Select for only datapoints with target value, Mean streambed embeddedness (%)
epa_0809_emd = epa_0809_phab.dropna(subset = ['Mean streambed embeddedness (%)'], axis = 0)
epa_1314_emd = epa_1314_phab.dropna(subset = ['Mean streambed embeddedness (%)'], axis = 0)
epa_1819_emd = epa_1819_phab.dropna(subset = ['Mean streambed embeddedness (%)'], axis = 0)

In [4]:
# Print number of rows in each dataset
print("Shape of epa 0809:", epa_0809_emd.shape)
print("Shape of epa 1314:", epa_1314_emd.shape)
print("Shape of epa 1819:", epa_1819_emd.shape)

Shape of epa 0809: (1435, 77)
Shape of epa 1314: (1322, 80)
Shape of epa 1819: (1225, 81)

# Step 3. Merge invidual years

### 2008-2009

In [5]:
#Merge 2008 - 2009 datasets
#Find first set of common columns
common0809_1 = list(set(epa_0809_emd.columns).intersection(epa_0809_land.columns))
#Merge 2008 - 2009 embeddedness with land data
epa_0809_mrg1 = epa_0809_emd.merge(epa_0809_land,
                                  on = common0809_1,
                                  how = 'left')
#Print first 2008 - 2009 dataframe
epa_0809_mrg1

,Unique ID,Site ID,Collection Date,Year,LAT_DD83,LON_DD83,Mean Bank Angle (degrees),Median Bank Angle (Degrees),Mean Undercut Distance (m),Median Undercut Distance,...,Maximum percent slope,Mean percent slope,Minimum percent slope,Mean percent tree canopy,Mean percent impervious surface,Mean percent sand,% hay/pasture,"% Low Intensity, High Intensity, Commercial/Industrial/Transportation, or Developed High Intensity","% Deciduous Forest, Evergreen Forest, or Mixed Forest",% Shrub/Scrub or Grasslands/Herbaceous
0,10000,FW08KS001,2008-08-05,2008,39.014908,-98.010465,30.863636,31.0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10001,FW08KS003,2008-08-11,2008,37.395285,-98.926280,19.681818,21.0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10002,FW08KS005,2008-07-22,2008,38.198927,-95.427684,30.636364,23.5,0.027273,0.0,...,5.1,1.241,0.0,7.452,0.731,6.504,74.404,5.156,9.362,10.276
3,10003,FW08KS006,2008-08-12,2008,37.477020,-98.365341,50.545455,49.5,0.067727,0.0,...,8.9,1.000,0.0,1.282,0.221,59.454,53.398,3.405,0.850,41.407
4,10004,FW08KS012,2008-07-15,2008,37.786624,-96.429970,32.272727,30.0,0.000000,0.0,...,22.5,3.812,0.0,2.157,0.330,6.934,6.461,2.496,2.470,87.417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,9832,FW08CA015,2008-06-03,2008,32.899619,-116.588742,30.090909,30.0,0.000000,0.0,...,40.8,13.545,0.0,27.183,0.216,46.954,0.000,4.403,31.536,64.000
1431,9920,FW08DE001,2008-07-14,2008,39.358843,-75.675494,11.136364,10.0,0.000000,0.0,...,3.7,0.776,0.0,40.480,0.346,29.000,43.981,5.054,38.616,1.120
1432,9922,FW08DE008,2008-07-08,2008,38.829692,-75.646277,27.000000,25.5,0.005556,0.0,...,1.3,0.274,0.0,44.763,0.216,67.197,35.083,5.032,46.010,6.902
1433,9923,FW08DE015,2008-07-07,2008,38.822414,-75.430403,26.954545,26.0,0.000000,0.0,...,1.3,0.102,0.0,41.431,2.773,80.862,31.254,11.907,23.741,16.655
1434,9924,FW08DE021,2008-07-29,2008,39.702790,-75.694040,30.545455,25.0,0.027273,0.0,...,18.4,4.426,0.0,21.693,11.494,30.507,5.135,66.086,24.666,3.295

In [6]:
#Find third set of common columns
common0809_2 = list(set(epa_0809_mrg1.columns).intersection(epa_0809_chem.columns))
#Merge 2008 - 2009 embeddedness with chem data
epa_0809_mrg2 = epa_0809_mrg1.merge(epa_0809_chem,
                                  on = common0809_2,
                                  how = 'left')
#Print second 2008-2009 dataframe
epa_0809_mrg2

,Unique ID,Site ID,Collection Date,Year,LAT_DD83,LON_DD83,Mean Bank Angle (degrees),Median Bank Angle (Degrees),Mean Undercut Distance (m),Median Undercut Distance,...,Ammonia (mg N/L),Nitrite (mg N/L),Nitrate (mg N/L),Total Nitrogen (mg N/L),pH,Total Phosphorus (ug/L),Silica (mg/L),Sulfate (mg/L),Total Suspended Solids (mg/L),Turbidity (NTU)
0,10000,FW08KS001,2008-08-05,2008,39.014908,-98.010465,30.863636,31.0,0.000000,0.0,...,0.020,0.00000,0.81812,1316.0,8.24,63.7256,19.129,260.24,24.7,6.600
1,10001,FW08KS003,2008-08-11,2008,37.395285,-98.926280,19.681818,21.0,0.000000,0.0,...,0.012,0.00583,1.96961,2219.0,8.26,67.6794,25.797,54.53,16.9,8.470
2,10002,FW08KS005,2008-07-22,2008,38.198927,-95.427684,30.636364,23.5,0.027273,0.0,...,0.367,0.00309,0.04569,2024.0,7.76,387.3913,13.199,8.06,460.8,433.000
3,10003,FW08KS006,2008-08-12,2008,37.477020,-98.365341,50.545455,49.5,0.067727,0.0,...,0.035,0.01126,3.36978,3963.0,8.33,138.0413,25.265,17.29,87.0,32.600
4,10004,FW08KS012,2008-07-15,2008,37.786624,-96.429970,32.272727,30.0,0.000000,0.0,...,0.012,0.00000,0.21067,362.0,8.27,36.6900,10.371,13.40,34.6,16.100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,9832,FW08CA015,2008-06-03,2008,32.899619,-116.588742,30.090909,30.0,0.000000,0.0,...,0.004,0.00000,0.02787,154.0,8.24,25.3113,34.850,44.89,0.0,0.961
1431,9920,FW08DE001,2008-07-14,2008,39.358843,-75.675494,11.136364,10.0,0.000000,0.0,...,0.168,0.01016,1.36328,1936.0,7.38,106.2713,10.513,8.74,6.1,8.540
1432,9922,FW08DE008,2008-07-08,2008,38.829692,-75.646277,27.000000,25.5,0.005556,0.0,...,0.050,0.00000,0.00729,749.0,6.80,65.3725,7.939,1.30,16.6,19.000
1433,9923,FW08DE015,2008-07-07,2008,38.822414,-75.430403,26.954545,26.0,0.000000,0.0,...,0.286,0.00000,0.00639,1194.0,7.06,68.0825,3.044,2.01,4.9,14.700
1434,9924,FW08DE021,2008-07-29,2008,39.702790,-75.694040,30.545455,25.0,0.027273,0.0,...,0.009,0.00000,1.17647,2127.0,8.11,36.4806,11.937,13.99,0.0,0.930

### 2013-2014

In [7]:
#Merge 2013 - 2014 datasets
#Find first set of common columns
common1314_1 = list(set(epa_1314_emd.columns).intersection(epa_1314_land.columns))
#Merge 2013 - 2014 embeddedness with land data
epa_1314_mrg1 = epa_1314_emd.merge(epa_1314_land,
                                  on = common1314_1,
                                  how = 'left')
#Print first 2013 - 2014 dataframe
epa_1314_mrg1

,Unique ID,Site ID,Collection Date,Year,LAT_DD83,LON_DD83,Mean Bank Angle (degrees),Median Bank Angle (Degrees),Mean Undercut Distance (m),Median Undercut Distance (m),...,"% developed, open space",Watershed mean of the high values of permeability,Mean annual precip for the watershed,Site mean of the high values of depth to bedrock,Watershed mean of the high values of depth to bedrock,NHDPlus COMID for the stream reach,Estimated watershed annual runoff,Topographic wetness index,Percent urban land use within 1 km,Watershed area in square kilometers
0,1002013,KSRS-1288,2013-04-30,2013,39.12843,-95.65402,31.727273,32.5,0.000000,0.0,...,9.721218,0.688000,954.499735,54.000000,54.000000,3645992.0,235.000000,440.230096,13.416764,22.4163
1,1002014,AZR9-0903,2013-05-06,2013,32.40882,-111.16060,78.500000,90.0,7.615385,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1002015,AZSS-1115,2013-05-07,2013,34.33749,-111.01380,25.000000,18.5,23.700000,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1002016,KSR9-0910,2013-05-06,2013,39.49523,-97.23190,27.500000,26.0,0.018182,0.0,...,3.131999,4.491908,530.950559,60.000000,58.995585,5926470.0,11.724365,542.726533,0.000000,56605.9833
4,1002017,AZLS-1055,2013-05-08,2013,34.86995,-112.06930,8.769231,6.0,16.538462,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1317,1004871,MNSS-1172,2014-08-27,2014,47.89590,-90.78157,21.619048,15.0,0.000000,0.0,...,1.428571,4.924000,770.090506,36.848000,36.848000,4797450.0,313.000000,475.481618,0.000000,0.2448
1318,1004951,RILS-1029,2014-06-23,2014,41.58105,-71.72228,55.181818,36.0,0.400000,0.3,...,4.190306,9.945080,1224.281989,56.500000,56.566431,6140288.0,699.190705,467.523394,2.769679,49.3596
1319,1004952,SDRF-0001,2014-06-23,2014,45.46337,-97.04395,63.636364,54.0,0.084091,0.0,...,2.362435,1.372278,622.075056,60.000000,60.000000,4081850.0,48.747298,379.424674,0.000000,15.4071
1320,1004954,IARF-0001,2014-06-24,2014,42.11479,-93.56017,38.318182,35.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1321,1004956,KSRF-0007,2014-06-26,2014,39.08611,-95.29009,30.045455,30.0,NaN,NaN,...,3.337053,0.951382,982.027829,42.400002,50.271135,3729225.0,230.867315,396.816116,0.000000,42.7329

In [8]:
#Find second set of common columns
common1314_2 = list(set(epa_1314_mrg1.columns).intersection(epa_1314_chem.columns))
#Merge 2013 - 2014 embeddedness with chem data
epa_1314_mrg2 = epa_1314_mrg1.merge(epa_1314_chem,
                                  on = common1314_2,
                                  how = 'left')
#Print first 2013 - 2014 dataframe
epa_1314_mrg2

,Unique ID,Site ID,Collection Date,Year,LAT_DD83,LON_DD83,Mean Bank Angle (degrees),Median Bank Angle (Degrees),Mean Undercut Distance (m),Median Undercut Distance (m),...,Nitrite (mg N/L),Nitrite (mg N/L).1,pH,Potassium (mg/L),Dissolved Total Phosphorus (ug/L),Silica (mg/L),Sodium (mg/L),Sulfate (mg/L),Total Suspended Solids (mg/L),Turbidity (NTU)
0,1002013,KSRS-1288,2013-04-30,2013,39.12843,-95.65402,31.727273,32.5,0.000000,0.0,...,0.000,0.000,7.88,3.664,59.0,8.977,114.300,105.096,6.5,3.50
1,1002014,AZR9-0903,2013-05-06,2013,32.40882,-111.16060,78.500000,90.0,7.615385,0.5,...,6.069,0.310,7.86,19.610,3269.0,36.988,153.400,151.101,17.2,5.70
2,1002015,AZSS-1115,2013-05-07,2013,34.33749,-111.01380,25.000000,18.5,23.700000,18.0,...,0.021,0.000,7.84,0.579,18.0,6.979,2.130,19.442,0.6,1.16
3,1002016,KSR9-0910,2013-05-06,2013,39.49523,-97.23190,27.500000,26.0,0.018182,0.0,...,0.304,0.000,8.33,11.940,311.0,16.819,85.550,106.315,49.4,28.78
4,1002017,AZLS-1055,2013-05-08,2013,34.86995,-112.06930,8.769231,6.0,16.538462,17.0,...,0.039,0.000,8.00,1.160,32.0,15.768,5.320,4.139,0.8,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1317,1004871,MNSS-1172,2014-08-27,2014,47.89590,-90.78157,21.619048,15.0,0.000000,0.0,...,0.000,0.000,6.46,0.143,12.0,2.193,0.646,0.429,3.1,1.74
1318,1004951,RILS-1029,2014-06-23,2014,41.58105,-71.72228,55.181818,36.0,0.400000,0.3,...,0.127,0.000,6.91,0.911,64.0,8.135,4.812,3.371,0.2,0.41
1319,1004952,SDRF-0001,2014-06-23,2014,45.46337,-97.04395,63.636364,54.0,0.084091,0.0,...,0.029,0.000,8.37,3.889,126.0,29.190,8.870,299.236,6.4,2.40
1320,1004954,IARF-0001,2014-06-24,2014,42.11479,-93.56017,38.318182,35.0,NaN,NaN,...,16.862,0.014,8.30,2.322,271.0,20.781,6.339,20.670,62.6,11.36
1321,1004956,KSRF-0007,2014-06-26,2014,39.08611,-95.29009,30.045455,30.0,NaN,NaN,...,0.608,0.000,7.98,3.842,151.0,13.652,8.798,39.912,24.0,10.80

### 2018-2019

In [9]:
#Find first set of common columns
common1819_1 = list(set(epa_1819_emd.columns).intersection(epa_1819_siteinfo.columns))
#Merge 2018 - 2019 embeddedness with site info data
epa_1819_mrg1 = epa_1819_emd.merge(epa_1819_siteinfo,
                                  on = common1819_1,
                                  how = 'left')
#Print second 2018 - 2019 dataframe
epa_1819_mrg1

,UNIQUE_ID,Unique ID,Site ID,Collection Date,Year,Mean Bank Angle (degrees),Median Bank Angle (Degrees),Mean Undercut Distance (m),Mid-channel Canopy Density (%),Bank Canopy Density (%),...,Embeddedness Center of Channel (Mean % wetted streambed),Mean Residual Depth at thalweg (cm).1,Ground layer Vegetated areal cover,Riparian Veg Quality Index--Scaled XCMGW,Riparian Veg Quality Index--Scaled XCDENBK,Riparian Disturbance index (scaled W1_Hall 0-1),Riparian Disturbance index (1 - RDIST1),Riparian Quality Index (Scaled 0 to 1),Elevation,Reach Code
0,NRS_OK-10090,2014737,NRS18_OK_10062,2018-06-20,2018,27.727273,20.0,0.000000,100.000000,100.000000,...,100.000000,14.553329,0.429004,0.309659,1.000000,0.000000,1.000000,0.676542,663.935,R11130301000258
1,NRS_OK-10206,2012488,NRS18_OK_10431,2018-06-25,2018,33.590909,23.5,0.000000,74.064171,76.737968,...,47.272727,19.747592,0.445455,0.488125,0.790642,0.614035,0.385965,0.530094,240.810,R11070209000527
2,NRS_OK-10180,2012489,NRS18_OK_10025,2018-07-02,2018,19.318182,10.0,0.000000,12.032086,67.112299,...,96.969697,67.406908,0.137500,0.505511,0.704011,0.000000,1.000000,0.708658,140.370,R11140102000005
3,NRS_WI-10211,2012490,NRS18_WI_10091,2018-07-02,2018,31.954545,30.0,0.042857,52.941176,79.144385,...,52.727273,23.075304,0.785227,0.347500,0.812299,0.714904,0.285096,0.431738,241.030,R07090004000666
4,NRS_WI-10087,2012491,NRS18_WI_10006,2018-07-12,2018,27.823529,20.0,2.076471,52.058824,97.213622,...,78.148148,13.440498,0.800000,0.759659,0.974923,0.555558,0.444442,0.690454,254.750,R04030108000203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,NRS_PA-10045,2014708,NRS18_PA_10009,2019-09-25,2019,22.227273,21.0,0.000000,10.294118,78.342246,...,27.575758,29.974738,0.806818,0.471250,0.805080,0.572819,0.427181,0.545215,310.040,R02050104000168
1221,NRS_SD-10328,2014714,NRS18_SD_10005,2019-09-25,2019,26.166667,20.0,0.169583,38.848039,59.803922,...,57.638889,13.767842,0.475000,0.380312,0.638235,0.400010,0.599989,0.526124,451.335,R10140101000419
1222,NRS_NC-10457,2014715,NRS18_NC_10897,2019-09-24,2019,57.523810,60.0,0.000000,51.871658,87.165775,...,100.000000,30.350296,0.545455,0.457955,0.884492,0.535219,0.464781,0.573132,205.320,R03040101000046
1223,NRS_ND-10267,2014720,NRS18_ND_10049,2019-09-27,2019,35.523810,35.0,0.065000,0.000000,70.868347,...,58.275862,NaN,0.939773,0.215568,0.737815,0.571441,0.428559,0.408490,521.290,R10130203000014
1224,NRS_MN-10220,2014734,NRS18_MN_10261,2019-10-02,2019,24.045455,18.0,0.018182,41.310160,69.786096,...,13.800000,NaN,0.780682,0.580170,0.728075,0.000000,1.000000,0.750315,387.970,R04010102000108

In [10]:
# Find second set of common columns
common1819_2 = list(set(epa_1819_mrg1.columns).intersection(epa_1819_land.columns))
#Merge 2018 - 2019 embeddedness with land data
epa_1819_mrg2 = epa_1819_mrg1.merge(epa_1819_land,
                                  on = common1819_2,
                                  how = 'left')
#Print second 2018 - 2019 dataframe
epa_1819_mrg2

,UNIQUE_ID,Unique ID,Site ID,Collection Date,Year,Mean Bank Angle (degrees),Median Bank Angle (Degrees),Mean Undercut Distance (m),Mid-channel Canopy Density (%),Bank Canopy Density (%),...,Horton overland flow,Watershed mean of the high values of permeability,Mean of all permeability values,Site mean of the high values of depth to bedrock,Watershed mean of the high values of depth to bedrock,Estimated watershed annual runoff,Mean of all sand values within watershed,Mean of all S values within watershed,Mean Composite Topographic Index (CTI)[Wetness Index],Watershed area in square kilometers
0,NRS_OK-10090,2014737,NRS18_OK_10062,2018-06-20,2018,27.727273,20.0,0.000000,100.000000,100.000000,...,23.797886,5.793185,9.769987,59.500000,59.941407,15.044169,64.408843,0.064549,783.256509,10.4733
1,NRS_OK-10206,2012488,NRS18_OK_10431,2018-06-25,2018,33.590909,23.5,0.000000,74.064171,76.737968,...,14.686742,1.655669,2.675900,58.293652,51.755819,316.444229,15.516805,0.325987,854.012910,13.9428
2,NRS_OK-10180,2012489,NRS18_OK_10025,2018-07-02,2018,19.318182,10.0,0.000000,12.032086,67.112299,...,11.814687,1.953064,3.228464,60.000000,54.514920,258.166777,19.686933,0.312495,855.466717,1597.0914
3,NRS_WI-10211,2012490,NRS18_WI_10091,2018-07-02,2018,31.954545,30.0,0.042857,52.941176,79.144385,...,5.816515,1.965846,3.270596,52.000000,52.233145,268.000000,17.471702,0.163090,781.569154,4.8609
4,NRS_WI-10087,2012491,NRS18_WI_10006,2018-07-12,2018,27.823529,20.0,2.076471,52.058824,97.213622,...,0.151444,13.587471,22.023520,48.000000,58.587236,282.252458,75.406769,0.036764,882.425172,656.5770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,NRS_PA-10045,2014708,NRS18_PA_10009,2019-09-25,2019,22.227273,21.0,0.000000,10.294118,78.342246,...,2.303129,2.296911,3.784093,60.000000,54.016029,384.760318,24.753182,0.173067,745.453162,726.5844
1221,NRS_SD-10328,2014714,NRS18_SD_10005,2019-09-25,2019,26.166667,20.0,0.169583,38.848039,59.803922,...,45.833549,0.748444,1.095456,36.799999,44.478486,18.789761,9.570218,0.291374,749.269473,55.7622
1222,NRS_NC-10457,2014715,NRS18_NC_10897,2019-09-24,2019,57.523810,60.0,0.000000,51.871658,87.165775,...,6.575107,2.186895,3.579674,58.299999,53.466681,487.483833,28.659459,0.033939,756.213330,473.3901
1223,NRS_ND-10267,2014720,NRS18_ND_10049,2019-09-27,2019,35.523810,35.0,0.065000,0.000000,70.868347,...,11.181765,2.325812,3.747545,45.000000,47.750972,22.973669,23.014958,0.382997,838.006536,690.3108
1224,NRS_MN-10220,2014734,NRS18_MN_10261,2019-10-02,2019,24.045455,18.0,0.018182,41.310160,69.786096,...,3.323806,3.843191,5.922506,59.368000,59.718441,365.058980,48.307078,0.045022,900.527207,50.0661

In [11]:
# Find third set of common columns
common1819_3 = list(set(epa_1819_mrg2.columns).intersection(epa_1819_chem.columns))
#Merge 2018 - 2019 embeddedness with chem data
epa_1819_mrg3 = epa_1819_mrg2.merge(epa_1819_chem,
                                  on = common1819_3,
                                  how = 'left')
#Print second 2018 - 2019 dataframe
epa_1819_mrg3

,UNIQUE_ID,Unique ID,Site ID,Collection Date,Year,Mean Bank Angle (degrees),Median Bank Angle (Degrees),Mean Undercut Distance (m),Mid-channel Canopy Density (%),Bank Canopy Density (%),...,Total Nitrogen (mg N/L),pH,Potassium (mg/L),Dissolved Total Phosphorus (ug/L),Total Phosphorus (ug/L),Silica (mg/L),Sodium (mg/L),Sulfate (mg/L),Total Suspended Solids (mg/L),Turbidity (NTU)
0,NRS_OK-10090,2014737,NRS18_OK_10062,2018-06-20,2018,27.727273,20.0,0.000000,100.000000,100.000000,...,3.240,8.06,2.320,NaN,223.000,30.500,55.900,20.400,264,123.00
1,NRS_OK-10206,2012488,NRS18_OK_10431,2018-06-25,2018,33.590909,23.5,0.000000,74.064171,76.737968,...,0.257,7.84,4.530,NaN,55.000,6.650,23.700,365.000,23,15.80
2,NRS_OK-10180,2012489,NRS18_OK_10025,2018-07-02,2018,19.318182,10.0,0.000000,12.032086,67.112299,...,0.305,8.42,1.760,NaN,50.000,8.650,6.550,8.200,18,15.60
3,NRS_WI-10211,2012490,NRS18_WI_10091,2018-07-02,2018,31.954545,30.0,0.042857,52.941176,79.144385,...,8.620,NaN,5.190,NaN,199.000,15.800,9.640,22.200,8,7.68
4,NRS_WI-10087,2012491,NRS18_WI_10006,2018-07-12,2018,27.823529,20.0,2.076471,52.058824,97.213622,...,0.278,8.17,1.250,NaN,17.900,10.800,3.060,7.230,NaN,2.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,NRS_PA-10045,2014708,NRS18_PA_10009,2019-09-25,2019,22.227273,21.0,0.000000,10.294118,78.342246,...,0.381,7.73,2.080,5.783,10.433,3.300,8.452,30.529,0.8,1.40
1221,NRS_SD-10328,2014714,NRS18_SD_10005,2019-09-25,2019,26.166667,20.0,0.169583,38.848039,59.803922,...,2.481,8.12,40.237,18.619,85.764,17.504,115.192,1727.158,95.3,68.43
1222,NRS_NC-10457,2014715,NRS18_NC_10897,2019-09-24,2019,57.523810,60.0,0.000000,51.871658,87.165775,...,4.288,7.79,7.065,282.605,340.111,18.387,50.055,23.809,3.9,3.14
1223,NRS_ND-10267,2014720,NRS18_ND_10049,2019-09-27,2019,35.523810,35.0,0.065000,0.000000,70.868347,...,1.678,8.31,14.045,136.981,217.090,14.030,207.517,492.481,17.3,20.77
1224,NRS_MN-10220,2014734,NRS18_MN_10261,2019-10-02,2019,24.045455,18.0,0.018182,41.310160,69.786096,...,0.813,7.75,0.945,21.448,39.093,12.543,4.352,0.705,3.7,3.35

## Step 3. Merge Model Building datasets

### Step 3a. Drop columns with more than 5% of data missing from each year's datasets

In [12]:
pd.set_option('display.max_rows', 5)

In [13]:
missing_0809 = epa_0809_mrg2.isnull().mean()
missing_1314 = epa_1314_mrg2.isnull().mean()
missing_1819 = epa_1819_mrg3.isnull().mean()

In [14]:
# Drop columns where the missing percentages are more than 10% of the column (0.05
epa_0809_cln = epa_0809_mrg2.drop(columns = missing_0809[missing_0809 > 0.05].index)
epa_1314_cln = epa_1314_mrg2.drop(columns = missing_1314[missing_1314 > 0.05].index)
epa_1819_cln = epa_1819_mrg3.drop(columns = missing_1819[missing_1819 > 0.05].index)

In [15]:
# Print new datasets
epa_0809_cln

,Unique ID,Site ID,Collection Date,Year,LAT_DD83,LON_DD83,Mean Bank Angle (degrees),Median Bank Angle (Degrees),Mid-channel Canopy Density (%),Bank Canopy Density (%),...,Ammonia (mg N/L),Nitrite (mg N/L),Nitrate (mg N/L),Total Nitrogen (mg N/L),pH,Total Phosphorus (ug/L),Silica (mg/L),Sulfate (mg/L),Total Suspended Solids (mg/L),Turbidity (NTU)
0,10000,FW08KS001,2008-08-05,2008,39.014908,-98.010465,30.863636,31.0,89.572193,94.919786,...,0.020,0.00000,0.81812,1316.0,8.24,63.7256,19.129,260.24,24.7,6.60
1,10001,FW08KS003,2008-08-11,2008,37.395285,-98.926280,19.681818,21.0,54.545455,52.941176,...,0.012,0.00583,1.96961,2219.0,8.26,67.6794,25.797,54.53,16.9,8.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1433,9923,FW08DE015,2008-07-07,2008,38.822414,-75.430403,26.954545,26.0,80.213904,80.748663,...,0.286,0.00000,0.00639,1194.0,7.06,68.0825,3.044,2.01,4.9,14.70
1434,9924,FW08DE021,2008-07-29,2008,39.702790,-75.694040,30.545455,25.0,84.090909,91.711230,...,0.009,0.00000,1.17647,2127.0,8.11,36.4806,11.937,13.99,0.0,0.93

In [16]:
epa_1314_cln

,Unique ID,Site ID,Collection Date,Year,LAT_DD83,LON_DD83,Mean Bank Angle (degrees),Median Bank Angle (Degrees),Mid-channel Canopy Density (%),Bank Canopy Density (%),...,Magnesium (mg/L),Nitrite (mg N/L),pH,Potassium (mg/L),Dissolved Total Phosphorus (ug/L),Silica (mg/L),Sodium (mg/L),Sulfate (mg/L),Total Suspended Solids (mg/L),Turbidity (NTU)
0,1002013,KSRS-1288,2013-04-30,2013,39.12843,-95.65402,31.727273,32.5,40.641711,64.705882,...,20.33,0.000,7.88,3.664,59.0,8.977,114.300,105.096,6.5,3.50
1,1002014,AZR9-0903,2013-05-06,2013,32.40882,-111.16060,78.500000,90.0,9.358289,37.165775,...,10.59,6.069,7.86,19.610,3269.0,36.988,153.400,151.101,17.2,5.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1320,1004954,IARF-0001,2014-06-24,2014,42.11479,-93.56017,38.318182,35.0,83.155080,94.652406,...,24.86,16.862,8.30,2.322,271.0,20.781,6.339,20.670,62.6,11.36
1321,1004956,KSRF-0007,2014-06-26,2014,39.08611,-95.29009,30.045455,30.0,69.919786,87.967914,...,14.15,0.608,7.98,3.842,151.0,13.652,8.798,39.912,24.0,10.80

In [17]:
epa_1819_cln

,UNIQUE_ID,Unique ID,Site ID,Collection Date,Year,Mean Bank Angle (degrees),Median Bank Angle (Degrees),Mid-channel Canopy Density (%),Bank Canopy Density (%),Constraining Features,...,Nitrate (mg N/L),Total Nitrogen (mg N/L),pH,Potassium (mg/L),Total Phosphorus (ug/L),Silica (mg/L),Sodium (mg/L),Sulfate (mg/L),Total Suspended Solids (mg/L),Turbidity (NTU)
0,NRS_OK-10090,2014737,NRS18_OK_10062,2018-06-20,2018,27.727273,20.0,100.000000,100.000000,TERRACE,...,1.5700,3.240,8.06,2.320,223.000,30.500,55.900,20.400,264,123.00
1,NRS_OK-10206,2012488,NRS18_OK_10431,2018-06-25,2018,33.590909,23.5,74.064171,76.737968,TERRACE,...,0.1330,0.257,7.84,4.530,55.000,6.650,23.700,365.000,23,15.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1223,NRS_ND-10267,2014720,NRS18_ND_10049,2019-09-27,2019,35.523810,35.0,0.000000,70.868347,NOCONST,...,0.1685,1.678,8.31,14.045,217.090,14.030,207.517,492.481,17.3,20.77
1224,NRS_MN-10220,2014734,NRS18_MN_10261,2019-10-02,2019,24.045455,18.0,41.310160,69.786096,HILLSLOPE,...,0.0098,0.813,7.75,0.945,39.093,12.543,4.352,0.705,3.7,3.35

In [18]:
# Find the common and unique columns between all three datasets
common_columns = set(epa_0809_cln.columns).intersection(epa_1314_cln.columns).intersection(epa_1819_cln.columns)
unique_columns_0809 = set(epa_0809_cln.columns) - common_columns
unique_columns_1314 = set(epa_1314_cln.columns) - common_columns
unique_columns_1819 = set(epa_1819_cln.columns) - common_columns

print("Common columns:", common_columns)

Common columns: {'Sulfate (mg/L)', 'Near Stream Human Dist: Pasture/Hayfield (distance-wtd tally of presence)', 'Mid-Layer Herbaceous areal cover', 'Instream Cover: Rocks and Ledges (areal proportion)', 'Magnesium (mg/L)', 'Instream Cover Sum: non-anthropogenic cover types (areal proportion)', 'Acid Neutralizing Capacity (UEQ/L)', 'Sum of Canopy+Mid layer vegetation areal cover proportion', 'Sum of Canopy+Mid+Ground layer areal cover proportion', 'Total Suspended Solids (mg/L)', 'Median Bank Angle (Degrees)', 'Large diameter (Dbh>0.3m) Tree Canopy Areal Cover proportion', 'Calcium (mg/L)', 'Mean Bankfull Height above wetted channel (m)', 'Filamentous algae Mean areal cover', 'Embeddedness Center of Channel (Mean % wetted streambed)', 'Silica (mg/L)', 'pH', '% Slow Water Habitat', 'Color (APHA PT-CO)', 'Mean Wetted Width (m)', 'Sum of Woody Canopy+Mid layer vegetation areal cover proportion', 'Mean streambed embeddedness (%)', 'Dissolved Oxygen Carbon (mg/L)', 'Year', 'Mean Bankfull Width (m)', 'Bankfull Width/Depth Ratio', 'Instream Cover: Aquatic macrophytes (areal proportion)', 'Mean Slope of water surface (%)', 'Unique ID', 'Bank Canopy Density (%)', 'Ammonia (mg N/L)', 'Instream Cover: Large woody debris (areal proportion)', 'Instream Cover: Brush (areal proportion)', 'Constraining Features', 'Canopy Absent - proportion of reach', 'Sodium (mg/L)', 'Instream Cover: Overhanging Banks (areal proportion)', 'Canopy Mean Areal Cover proportion', '% Fast Water Habitat', 'Mean Bank Angle (degrees)', 'Riparian Veg Quality Index--Scaled XCMGW', 'Mean Wetted Width/Thalweg Depth ratio', 'Riparian Veg Quality Index--Scaled XCDENBK', 'Riparian Disturbance index (scaled W1_Hall 0-1)', 'Mean thalweg depth (cm)', 'Turbidity (NTU)', 'Human Non-Agric. Disturb. Index (distance wtd tally of types & presence)', 'Conductivity (uS/cm)', 'Human Disturbance Index(distance-wtd tally of types and presence)', 'Instream Cover Sum: All except algae and aquatic macrophytes (areal proportion)', 'Broadleaf Deciduous Canopy - proportion of reach', 'Woody ground layer areal cover', 'Mid-Layer Woody areal cover', 'Riparian Quality Index (Scaled 0 to 1)', 'Barren ground layer areal cover', 'Mid-channel Canopy Density (%)', 'Chloride (mg/L)', 'Site ID', 'Non-woody ground layer areal cover', 'Human Agricultural Influence Index(distancewtd tally of types & presence)', 'Mean Wetted Width x Thalweg depth', 'Instream Cover Sum: wood, boulders, overhang banks, human structures (areal proportion)', 'Sinuosity of sample reach', 'Potassium (mg/L)', 'Instream Cover: Overhanging Vegetation', 'Sum of Woody Canopy+Mid+Ground layer areal cover proportion', 'Collection Date', 'Mid-Layer areal cover', 'Mean Residual Depth at thalweg (cm)', 'Pools - % of Reach', 'Terrace Height above water level (m)'}

In [19]:
print("Unique columns in EPA 08/09:", unique_columns_0809)

Unique columns in EPA 08/09: {'Nitrite (mg N/L)', 'Nitrate (mg N/L)', 'LAT_DD83', 'LON_DD83', 'Canopy Presence: proportion of reach" "Canopy Presence: proportion of reach', 'Fish Cvr-Artif. Structs. (Areal Prop)', 'Total Nitrogen (mg N/L)', 'Total ground layer areal cover', 'Hydraulic resistance due to bed particles at bankfull', 'Total Phosphorus (ug/L)', 'Small diameter (Dbh<0.3m) Tree Canopy Areal Cover proportion'}

In [20]:
print("Unique columns in EPA 13/14:", unique_columns_1314)

Unique columns in EPA 13/14: {'Canopy+Mid+Ground-layer Presence: proportion of reach', 'Nitrite (mg N/L)', 'Ratio of Effective to Total Hydraulic Radii at Bankfull', 'Near Stream Human Dist: Buildings (distancewtd tally of presence)', 'Canopy Presence: proportion of reach', 'LON_DD83', 'Bankfull Channel Wood Count/100m Size=T+S+M+L+X (EPA/620/R-99/003 p53)', ' Dissolved Total Phosphorus (ug/L)', 'Mid-layer Presence: proportion of reach', 'LAT_DD83', 'Bankfull Channel Wood Volume (m3/m2) Size=S+M+L+X (EPA/620/R-99/003 p53)', 'Bankfull Channel Wood Volume (m3/100m) Size=S+M+L+X (EPA/620/R-99/003 p53)', 'Small diameter (Dbh', 'Bankfull Channel Wood Count/100m Size=S+M+L+X (EPA/620/R-99/003 p53)', 'Canopy+Mid-layer Presence: proportion of reach', 'Woody Canopy+Mid+Ground-layer Presence: proportion of reach', 'Bankfull Channel Wood Volume (m3/m2) Size=T+S+M+L+X (EPA/620/R-99/003 p53)', 'Total ground layer areal cover', 'Instream Cover: Live Trees (areal proportion)', '% Glide Habitat', 'Mean Slope of water surface-Field measurement (%)', 'Bankfull Channel Wood Volume (m3/100m) Size=T+S+M+L+X (EPA/620/R-99/003 p53)'}

In [21]:
print("Unique columns in EPA 18/19:", unique_columns_1819)

Unique columns in EPA 18/19: {'% developed, medium-intensity', '% of watershed classified as areas of bedrock, desert pavement, scarps, talus, slides, volcanic materical, glacial debris, sand dunes, strip mines, gravel pits, and accumulations of earthen material within 100-m buffer of NHD stream lines', '% shrub/scrub ', 'Bankfull+above Channel Wood Count/100m Size=T+S+M+L+X (EPA/620/R-99/003 p53)', 'Watershed mean of the high values of depth to bedrock', 'Mean of all lithological nitrogen (N) content in surface or near surface geology\nvalues within watershed ', 'Mean Residual Depth at thalweg (cm).1', '% developed, high-intensity', '% grassland/herbaceous', 'Canopy Presence: proportion of reach', 'UNIQUE_ID', '% of watershed areas classified as evergreen\nforest land cover and within 100-m buffer of NHD stream lines ', '% Sandstone', 'Mean surface soil erodibility factors adjusted (KFFACT) on agricultural land', '% Semiconsolidated sand', 'Maximum residual Depth (cm)', '% watershed areas classified as developed, medium intensity land use and within 100-m buffer of NHD stream lines', '% noncarbonate residual', 'Mid-layer Presence: proportion of reach', '% developed, open space', 'Canopy+Mid-layer Presence: proportion of reach', 'Elevation', 'PCTIMP2011WSRP100', 'Horton overland flow', 'Mean of all sand values within watershed', '% Glide Habitat', 'Elevation at gage location', 'Mean Slope of water surface-Field measurement (%)', 'Ground layer Vegetated areal cover', ' % mixed deciduous/evergreen forest', 'Reach Code', 'Total Nitrogen (mg N/L)', '% watershed areas classified as developed, high intensity land use and within 100-m buffer of NHD stream lines', 'Bankfull Channel Wood Count/100m Size=T+S+M+L+X (EPA/620/R-99/003 p53)', 'Site mean of the soil erodibility factor', 'Mean watershed elevation', 'Nitrate (mg N/L)', '% of watershed areas classified as grassland/herbaceous land cover and within 100-m buffer of NHD stream lines', 'Woody Canopy+Mid+Ground-layer Presence: proportion of reach', 'Bankfull Channel Wood Volume (m3/m2) Size=T+S+M+L+X (EPA/620/R-99/003 p53)', 'Small diameter (Dbh<0.3m) Tree Canopy Areal Cover proportion', 'Estimated watershed annual runoff', 'Mean rate of synthetic nitrogen fertilizer application to agricultural land, within watershed ', 'Mean of all S values within watershed', '% watershed areas classified as pasture/hay land use and within 100-m buffer of NHD stream lines', '% of watershed areas classified as open water land\ncover and within 100-m buffer of NHD stream lines ', 'Watershed mean of the high values of permeability', '% crop land', '% hay ', 'Riparian Disturbance index (1 - RDIST1)', '% silicic residual', '% watershed areas classified as developed, open space land use and within 100-m buffer of NHD stream lines', '% of watershed classified as lithology type:\nalluvium and fine-textured coastal zone sediment', '% of watershed areas classified as evergreen forest land cover', 'Near Stream Human Dist: Buildings (distancewtd tally of presence)', '% deciduous forest', '% open water', '%  watershed areas classified as shrub/scrub land cover and within 100-m buffer of NHD stream lines', 'Mean maximum depth of residual Pools in reach (cm)', 'Mean high values of soil bulk density', 'Base Flow Index ', 'Bankfull Channel Wood Volume (m3/m2) Size=S+M+L+X (EPA/620/R-99/003 p53)', '% of watershed classified as areas of bedrock, desert pavement, scarps, talus, slides, volcanic materical, glacial debris, sand dunes, strip mines, gravel pits, and accumulations of earthen material', '% of watershed areas classified as deciduous forest land cover and within 100-m buffer of NHD stream lines', '% Unconsolidated sand and gravel', 'Mean imperviousness of anthropogenic surfaces within watershed', 'Watershed mean of the soil erodibility factor ', 'Minimum watershed elevation', 'Mean of all clay values within the upstream watershed', '% of watershed areas classified as developed, low intensity land use and within 100-m buffer of NHD stream lines', '% of watershed areas classified as row crop land use and within 100-m buffer of NHD stream lines', 'Mean Composite Topographic Index (CTI)[Wetness Index]', 'Mean of all hydraulic conductivity of surface\nor near surface geology values within watershed', '% developed, low-intensity', 'Canopy+Mid+Ground-layer Presence: proportion of reach', 'Site mean of the high values of depth to bedrock', '% Colluvial sediment in watershed', 'Maximum watershed elevation', 'Mean of all lithological magnesium oxide (MgO) content in surface or near surface\ngeology values within watershed', 'Mean imperviousness of anthropogenic surfaces within watershed and within 100-m buffer of NHD stream lines', 'Mean of all lithological potassium oxide (K2O) content in surface or near surface\ngeology values within watershed', 'Total Phosphorus (ug/L)', '% Carbonate residual in watershed', '% Carbonate rock in watershed', 'Bankfull Channel Wood Volume (m3/100m) Size=S+M+L+X (EPA/620/R-99/003 p53)', 'Watershed area in square kilometers', 'Mean of all permeability values', 'Mean of all lithological sodium oxide (Na2O) content in surface or near\nsurface geology values within watershed', '% Sandstone and carbonate rocks', 'Instream Cover: Live Trees (areal proportion)', 'Bankfull Channel Wood Volume (m3/100m) Size=T+S+M+L+X (EPA/620/R-99/003 p53)'}

### Step 3b. Rename columns for consistency

In [22]:
renaming_dict = {
    # General Standardizations
    "LAT_DD83": "Latitude (DD83)",
    "LON_DD83": "Longitude (DD83)",

    # For EPA 08/09
    "Canopy Presence: proportion of reach": "Canopy Presence (proportion of reach)",

    # For EPA 13/14
    "Small diameter (Dbh": "Small diameter (Dbh<0.3m) Tree Canopy Areal Cover proportion",
    " Dissolved Total Phosphorus (ug/L)": "Dissolved Total Phosphorus (ug/L)",

    # For EPA 18/19
    "Bankfull+above Channel Wood Count/100m Size=T+S+M+L+X": "Bankfull Channel Wood Count/100m Size=T+S+M+L+X",
    "Mean of all lithological potassium oxide (K2O) content in surface or near surface geology values within watershed": "Mean lithological potassium oxide (K2O) content in geology (watershed)",
    "Mean Residual Depth at thalweg (cm).1": "Mean Residual Depth at thalweg (cm)",
    "Small diameter (Dbh<0.3m) Tree Canopy Areal Cover proportion": "Small diameter (Dbh<0.3m) Tree Canopy Areal Cover proportion",  # to ensure uniformity
    "Bankfull Channel Wood Volume (m3/100m) Size=T+S+M+L+X (EPA/620/R-99/003 p53)": "Bankfull Channel Wood Volume (m³/100m) Size=T+S+M+L+X",
    "Bankfull Channel Wood Volume (m3/100m) Size=S+M+L+X (EPA/620/R-99/003 p53)": "Bankfull Channel Wood Volume (m³/100m) Size=S+M+L+X",
    "Bankfull Channel Wood Volume (m3/m2) Size=S+M+L+X (EPA/620/R-99/003 p53)": "Bankfull Channel Wood Volume (m³/m²) Size=S+M+L+X",
    "Bankfull Channel Wood Volume (m3/m2) Size=T+S+M+L+X (EPA/620/R-99/003 p53)": "Bankfull Channel Wood Volume (m³/m²) Size=T+S+M+L+X",

    # Consistency in Cover Types
    "Instream Cover: Live Trees (areal proportion)": "Instream Cover: Live Trees (areal proportion)",
    "Instream Cover: Aquatic macrophytes (areal proportion)": "Instream Cover: Aquatic Macrophytes (areal proportion)",
    "Instream Cover: Rocks and Ledges (areal proportion)": "Instream Cover: Rocks & Ledges (areal proportion)",
    "Instream Cover: Overhanging Vegetation": "Instream Cover: Overhanging Vegetation (areal proportion)",

    # Consistency in Index Terms
    "Riparian Veg Quality Index--Scaled XCDENBK": "Riparian Vegetation Quality Index (Scaled XCDENBK)",
    "Riparian Veg Quality Index--Scaled XCMGW": "Riparian Vegetation Quality Index (Scaled XCMGW)",
    "Riparian Disturbance index (1 - RDIST1)": "Riparian Disturbance Index (1 - RDIST1)",
    "Riparian Quality Index (Scaled 0 to 1)": "Riparian Quality Index (0-1 Scale)",
    
    # Streamlining Slope and Surface Measurements
    "Mean Slope of water surface (%)": "Mean Water Surface Slope (%)",
    "Mean Slope of water surface-Field measurement (%)": "Mean Water Surface Slope (Field %)",
    
    # Ammonia standardization
    "Ammonia (mg N/L)": "Ammonia (mg N/L)"
}

In [23]:
# Apply renaming dictionary to each dataset
epa_0809_cln2 = epa_0809_cln.rename(columns=renaming_dict)
epa_1314_cln2 = epa_1314_cln.rename(columns=renaming_dict)
epa_1819_cln2 = epa_1819_cln.rename(columns=renaming_dict)

### Step 3c. Try again with renaming

In [24]:
# Find the common and unique columns between all three datasets
common_columns = set(epa_0809_cln2.columns).intersection(epa_1314_cln2.columns).intersection(epa_1819_cln2.columns)
unique_columns_0809 = set(epa_0809_cln2.columns) - common_columns
unique_columns_1314 = set(epa_1314_cln2.columns) - common_columns
unique_columns_1819 = set(epa_1819_cln2.columns) - common_columns

print("Common columns:", common_columns)

Common columns: {'Sulfate (mg/L)', 'Near Stream Human Dist: Pasture/Hayfield (distance-wtd tally of presence)', 'Mid-Layer Herbaceous areal cover', 'Magnesium (mg/L)', 'Instream Cover Sum: non-anthropogenic cover types (areal proportion)', 'Instream Cover: Overhanging Vegetation (areal proportion)', 'Acid Neutralizing Capacity (UEQ/L)', 'Sum of Canopy+Mid layer vegetation areal cover proportion', 'Sum of Canopy+Mid+Ground layer areal cover proportion', 'Total Suspended Solids (mg/L)', 'Median Bank Angle (Degrees)', 'Large diameter (Dbh>0.3m) Tree Canopy Areal Cover proportion', 'Riparian Quality Index (0-1 Scale)', 'Calcium (mg/L)', 'Mean Bankfull Height above wetted channel (m)', 'Filamentous algae Mean areal cover', 'Embeddedness Center of Channel (Mean % wetted streambed)', 'Silica (mg/L)', 'pH', '% Slow Water Habitat', 'Color (APHA PT-CO)', 'Mean Water Surface Slope (%)', 'Mean Wetted Width (m)', 'Sum of Woody Canopy+Mid layer vegetation areal cover proportion', 'Mean streambed embeddedness (%)', 'Dissolved Oxygen Carbon (mg/L)', 'Year', 'Mean Bankfull Width (m)', 'Bankfull Width/Depth Ratio', 'Riparian Vegetation Quality Index (Scaled XCMGW)', 'Unique ID', 'Bank Canopy Density (%)', 'Ammonia (mg N/L)', 'Instream Cover: Large woody debris (areal proportion)', 'Instream Cover: Brush (areal proportion)', 'Constraining Features', 'Canopy Absent - proportion of reach', 'Sodium (mg/L)', 'Instream Cover: Overhanging Banks (areal proportion)', 'Canopy Mean Areal Cover proportion', '% Fast Water Habitat', 'Mean Bank Angle (degrees)', 'Riparian Disturbance index (scaled W1_Hall 0-1)', 'Mean Wetted Width/Thalweg Depth ratio', 'Turbidity (NTU)', 'Mean thalweg depth (cm)', 'Instream Cover: Rocks & Ledges (areal proportion)', 'Human Non-Agric. Disturb. Index (distance wtd tally of types & presence)', 'Small diameter (Dbh<0.3m) Tree Canopy Areal Cover proportion', 'Conductivity (uS/cm)', 'Human Disturbance Index(distance-wtd tally of types and presence)', 'Instream Cover Sum: All except algae and aquatic macrophytes (areal proportion)', 'Broadleaf Deciduous Canopy - proportion of reach', 'Woody ground layer areal cover', 'Mid-Layer Woody areal cover', 'Instream Cover: Aquatic Macrophytes (areal proportion)', 'Barren ground layer areal cover', 'Mid-channel Canopy Density (%)', 'Chloride (mg/L)', 'Site ID', 'Non-woody ground layer areal cover', 'Human Agricultural Influence Index(distancewtd tally of types & presence)', 'Mean Wetted Width x Thalweg depth', 'Instream Cover Sum: wood, boulders, overhang banks, human structures (areal proportion)', 'Sinuosity of sample reach', 'Potassium (mg/L)', 'Sum of Woody Canopy+Mid+Ground layer areal cover proportion', 'Collection Date', 'Riparian Vegetation Quality Index (Scaled XCDENBK)', 'Mid-Layer areal cover', 'Mean Residual Depth at thalweg (cm)', 'Pools - % of Reach', 'Terrace Height above water level (m)'}

In [25]:
print("Unique columns in EPA 08/09:", unique_columns_0809)

Unique columns in EPA 08/09: {'Nitrite (mg N/L)', 'Nitrate (mg N/L)', 'Latitude (DD83)', 'Canopy Presence: proportion of reach" "Canopy Presence: proportion of reach', 'Longitude (DD83)', 'Fish Cvr-Artif. Structs. (Areal Prop)', 'Total Nitrogen (mg N/L)', 'Total ground layer areal cover', 'Total Phosphorus (ug/L)', 'Hydraulic resistance due to bed particles at bankfull'}

In [26]:
print("Unique columns in EPA 13/14:", unique_columns_1314)

Unique columns in EPA 13/14: {'Canopy+Mid+Ground-layer Presence: proportion of reach', 'Nitrite (mg N/L)', 'Bankfull Channel Wood Volume (m³/100m) Size=S+M+L+X', 'Longitude (DD83)', 'Ratio of Effective to Total Hydraulic Radii at Bankfull', 'Bankfull Channel Wood Volume (m³/m²) Size=S+M+L+X', 'Bankfull Channel Wood Volume (m³/100m) Size=T+S+M+L+X', 'Near Stream Human Dist: Buildings (distancewtd tally of presence)', 'Bankfull Channel Wood Count/100m Size=T+S+M+L+X (EPA/620/R-99/003 p53)', 'Canopy Presence (proportion of reach)', 'Dissolved Total Phosphorus (ug/L)', 'Mid-layer Presence: proportion of reach', 'Latitude (DD83)', 'Bankfull Channel Wood Count/100m Size=S+M+L+X (EPA/620/R-99/003 p53)', 'Canopy+Mid-layer Presence: proportion of reach', 'Woody Canopy+Mid+Ground-layer Presence: proportion of reach', 'Total ground layer areal cover', 'Bankfull Channel Wood Volume (m³/m²) Size=T+S+M+L+X', 'Instream Cover: Live Trees (areal proportion)', '% Glide Habitat', 'Mean Water Surface Slope (Field %)'}

In [27]:
print("Unique columns in EPA 18/19:", unique_columns_1819)

Unique columns in EPA 18/19: {'% developed, medium-intensity', '% of watershed classified as areas of bedrock, desert pavement, scarps, talus, slides, volcanic materical, glacial debris, sand dunes, strip mines, gravel pits, and accumulations of earthen material within 100-m buffer of NHD stream lines', '% shrub/scrub ', 'Bankfull+above Channel Wood Count/100m Size=T+S+M+L+X (EPA/620/R-99/003 p53)', 'Watershed mean of the high values of depth to bedrock', 'Mean of all lithological nitrogen (N) content in surface or near surface geology\nvalues within watershed ', '% developed, high-intensity', '% grassland/herbaceous', 'UNIQUE_ID', '% of watershed areas classified as evergreen\nforest land cover and within 100-m buffer of NHD stream lines ', '% Sandstone', 'Mean surface soil erodibility factors adjusted (KFFACT) on agricultural land', '% Semiconsolidated sand', 'Maximum residual Depth (cm)', '% watershed areas classified as developed, medium intensity land use and within 100-m buffer of NHD stream lines', '% noncarbonate residual', 'Mid-layer Presence: proportion of reach', '% developed, open space', 'Canopy+Mid-layer Presence: proportion of reach', 'Elevation', 'PCTIMP2011WSRP100', 'Horton overland flow', 'Mean of all sand values within watershed', '% Glide Habitat', 'Elevation at gage location', 'Ground layer Vegetated areal cover', ' % mixed deciduous/evergreen forest', 'Reach Code', 'Total Nitrogen (mg N/L)', 'Bankfull Channel Wood Volume (m³/100m) Size=T+S+M+L+X', '% watershed areas classified as developed, high intensity land use and within 100-m buffer of NHD stream lines', 'Bankfull Channel Wood Count/100m Size=T+S+M+L+X (EPA/620/R-99/003 p53)', 'Site mean of the soil erodibility factor', 'Mean watershed elevation', 'Nitrate (mg N/L)', '% of watershed areas classified as grassland/herbaceous land cover and within 100-m buffer of NHD stream lines', 'Woody Canopy+Mid+Ground-layer Presence: proportion of reach', 'Estimated watershed annual runoff', 'Mean rate of synthetic nitrogen fertilizer application to agricultural land, within watershed ', 'Mean of all S values within watershed', '% watershed areas classified as pasture/hay land use and within 100-m buffer of NHD stream lines', 'Bankfull Channel Wood Volume (m³/m²) Size=T+S+M+L+X', '% of watershed areas classified as open water land\ncover and within 100-m buffer of NHD stream lines ', 'Watershed mean of the high values of permeability', '% crop land', '% hay ', '% silicic residual', 'Bankfull Channel Wood Volume (m³/100m) Size=S+M+L+X', '% watershed areas classified as developed, open space land use and within 100-m buffer of NHD stream lines', '% of watershed classified as lithology type:\nalluvium and fine-textured coastal zone sediment', '% of watershed areas classified as evergreen forest land cover', 'Near Stream Human Dist: Buildings (distancewtd tally of presence)', '% deciduous forest', '% open water', '%  watershed areas classified as shrub/scrub land cover and within 100-m buffer of NHD stream lines', 'Mean maximum depth of residual Pools in reach (cm)', 'Mean high values of soil bulk density', 'Base Flow Index ', '% of watershed classified as areas of bedrock, desert pavement, scarps, talus, slides, volcanic materical, glacial debris, sand dunes, strip mines, gravel pits, and accumulations of earthen material', '% of watershed areas classified as deciduous forest land cover and within 100-m buffer of NHD stream lines', '% Unconsolidated sand and gravel', 'Mean imperviousness of anthropogenic surfaces within watershed', 'Watershed mean of the soil erodibility factor ', 'Minimum watershed elevation', 'Mean of all clay values within the upstream watershed', '% of watershed areas classified as developed, low intensity land use and within 100-m buffer of NHD stream lines', '% of watershed areas classified as row crop land use and within 100-m buffer of NHD stream lines', 'Mean Composite Topographic Index (CTI)[Wetness Index]', 'Mean of all hydraulic conductivity of surface\nor near surface geology values within watershed', '% developed, low-intensity', 'Canopy+Mid+Ground-layer Presence: proportion of reach', 'Site mean of the high values of depth to bedrock', '% Colluvial sediment in watershed', 'Bankfull Channel Wood Volume (m³/m²) Size=S+M+L+X', 'Maximum watershed elevation', 'Mean of all lithological magnesium oxide (MgO) content in surface or near surface\ngeology values within watershed', 'Mean imperviousness of anthropogenic surfaces within watershed and within 100-m buffer of NHD stream lines', 'Canopy Presence (proportion of reach)', 'Riparian Disturbance Index (1 - RDIST1)', 'Mean of all lithological potassium oxide (K2O) content in surface or near surface\ngeology values within watershed', 'Total Phosphorus (ug/L)', '% Carbonate residual in watershed', '% Carbonate rock in watershed', 'Watershed area in square kilometers', 'Mean of all permeability values', 'Mean of all lithological sodium oxide (Na2O) content in surface or near\nsurface geology values within watershed', '% Sandstone and carbonate rocks', 'Instream Cover: Live Trees (areal proportion)', 'Mean Water Surface Slope (Field %)'}

In [28]:
common_columns = list(common_columns)
epa_mrg1 = pd.concat([epa_0809_cln2[common_columns],
                      epa_1314_cln2[common_columns],
                      epa_1819_cln2[common_columns]])
epa_mrg1

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [ ]:
common = set(epa_1314_cln2.columns).intersection(epa_1819_cln2.columns)
common

In [ ]:
unique_columns_1314 = set(epa_1314_cln2.columns) - common
unique_columns_1819 = set(epa_1819_cln2.columns) - common
unique_columns_1314

In [ ]:
unique_columns_1819

## Step 4. Export Relevant Datasets
We are going to move forward with the 2018-2019 dataset for the sake of model explainability.

In [30]:
epa_1819_cln2.to_excel('epa_2819_trimmed.xlsx')